const List<Map<String, String>> mimeTypeExtData = [
  {"extension": ".123", "meme_type": "application/vnd.lotus-1-2-3"},
  {"extension": ".3dml", "meme_type": "text/vnd.in3d.3dml"},
  {"extension": ".3g2", "meme_type": "video/3gpp2"},
  {"extension": ".3gp", "meme_type": "video/3gpp"},
  {"extension": ".a", "meme_type": "application/octet-stream"},
  {"extension": ".aab", "meme_type": "application/x-authorware-bin"},
  {"extension": ".aac", "meme_type": "audio/x-aac"},
  {"extension": ".aam", "meme_type": "application/x-authorware-map"},
  {"extension": ".aas", "meme_type": "application/x-authorware-seg"},
  {"extension": ".abw", "meme_type": "application/x-abiword"},
  {"extension": ".acc", "meme_type": "application/vnd.americandynamics.acc"},
  {"extension": ".ace", "meme_type": "application/x-ace-compressed"},
  {"extension": ".acu", "meme_type": "application/vnd.acucobol"},
  {"extension": ".acutc", "meme_type": "application/vnd.acucorp"},
  {"extension": ".adp", "meme_type": "audio/adpcm"},
  {"extension": ".aep", "meme_type": "application/vnd.audiograph"},
  {"extension": ".afm", "meme_type": "application/x-font-type1"},
  {"extension": ".afp", "meme_type": "application/vnd.ibm.modcap"},
  {"extension": ".ai", "meme_type": "application/postscript"},
  {"extension": ".aif", "meme_type": "audio/x-aiff"},
  {
    "extension": ".air",
    "meme_type": "application/vnd.adobe.air-application-installer-package+zip"
  },
  {"extension": ".ami", "meme_type": "application/vnd.amiga.ami"},
  {"extension": ".apk", "meme_type": "application/vnd.android.package-archive"},
  {"extension": ".application", "meme_type": "application/x-ms-application"},
  {"extension": ".apr", "meme_type": "application/vnd.lotus-approach"},
  {"extension": ".asc", "meme_type": "application/pgp-signature"},
  {"extension": ".asf", "meme_type": "video/x-ms-asf"},
  {"extension": ".asm", "meme_type": "text/x-asm"},
  {"extension": ".aso", "meme_type": "application/vnd.accpac.simply.aso"},
  {"extension": ".atom", "meme_type": "application/atom+xml"},
  {"extension": ".atomcat", "meme_type": "application/atomcat+xml"},
  {"extension": ".atomsvc", "meme_type": "application/atomsvc+xml"},
  {"extension": ".atx", "meme_type": "application/vnd.antix.game-component"},
  {"extension": ".au", "meme_type": "audio/basic"},
  {"extension": ".avi", "meme_type": "video/x-msvideo"},
  {"extension": ".aw", "meme_type": "application/applixware"},
  {"extension": ".azf", "meme_type": "application/vnd.airzip.filesecure.azf"},
  {"extension": ".azs", "meme_type": "application/vnd.airzip.filesecure.azs"},
  {"extension": ".azw", "meme_type": "application/vnd.amazon.ebook"},
  {"extension": ".bat", "meme_type": "application/x-msdownload"},
  {"extension": ".bcpio", "meme_type": "application/x-bcpio"},
  {"extension": ".bdf", "meme_type": "application/x-font-bdf"},
  {"extension": ".bdm", "meme_type": "application/vnd.syncml.dm+wbxml"},
  {"extension": ".bh2", "meme_type": "application/vnd.fujitsu.oasysprs"},
  {"extension": ".bmi", "meme_type": "application/vnd.bmi"},
  {"extension": ".bmp", "meme_type": "image/bmp"},
  {"extension": ".book", "meme_type": "application/vnd.framemaker"},
  {"extension": ".box", "meme_type": "application/vnd.previewsystems.box"},
  {"extension": ".boz", "meme_type": "application/x-bzip2"},
  {"extension": ".btif", "meme_type": "image/prs.btif"},
  {"extension": ".bz", "meme_type": "application/x-bzip"},
  {"extension": ".c", "meme_type": "text/x-c"},
  {"extension": ".c4d", "meme_type": "application/vnd.clonk.c4group"},
  {"extension": ".cab", "meme_type": "application/vnd.ms-cab-compressed"},
  {"extension": ".car", "meme_type": "application/vnd.curl.car"},
  {"extension": ".cat", "meme_type": "application/vnd.ms-pki.seccat"},
  {"extension": ".cct", "meme_type": "application/x-director"},
  {"extension": ".ccxml", "meme_type": "application/ccxml+xml"},
  {"extension": ".cdbcmsg", "meme_type": "application/vnd.contact.cmsg"},
  {"extension": ".cdf", "meme_type": "application/x-netcdf"},
  {"extension": ".cdkey", "meme_type": "application/vnd.mediastation.cdkey"},
  {"extension": ".cdx", "meme_type": "chemical/x-cdx"},
  {"extension": ".cdxml", "meme_type": "application/vnd.chemdraw+xml"},
  {"extension": ".cdy", "meme_type": "application/vnd.cinderella"},
  {"extension": ".cer", "meme_type": "application/pkix-cert"},
  {"extension": ".cgm", "meme_type": "image/cgm"},
  {"extension": ".chat", "meme_type": "application/x-chat"},
  {"extension": ".chm", "meme_type": "application/vnd.ms-htmlhelp"},
  {"extension": ".chrt", "meme_type": "application/vnd.kde.kchart"},
  {"extension": ".cif", "meme_type": "chemical/x-cif"},
  {
    "extension": ".cii",
    "meme_type": "application/vnd.anser-web-certificate-issue-initiation"
  },
  {"extension": ".cil", "meme_type": "application/vnd.ms-artgalry"},
  {"extension": ".cla", "meme_type": "application/vnd.claymore"},
  {"extension": ".class", "meme_type": "application/java-vm"},
  {"extension": ".clkk", "meme_type": "application/vnd.crick.clicker.keyboard"},
  {"extension": ".clkp", "meme_type": "application/vnd.crick.clicker.palette"},
  {"extension": ".clkt", "meme_type": "application/vnd.crick.clicker.template"},
  {"extension": ".clkw", "meme_type": "application/vnd.crick.clicker.wordbank"},
  {"extension": ".clkx", "meme_type": "application/vnd.crick.clicker"},
  {"extension": ".clp", "meme_type": "application/x-msclip"},
  {"extension": ".cmc", "meme_type": "application/vnd.cosmocaller"},
  {"extension": ".cmdf", "meme_type": "chemical/x-cmdf"},
  {"extension": ".cml", "meme_type": "chemical/x-cml"},
  {"extension": ".cmp", "meme_type": "application/vnd.yellowriver-custom-menu"},
  {"extension": ".cmx", "meme_type": "image/x-cmx"},
  {"extension": ".cod", "meme_type": "application/vnd.rim.cod"},
  {"extension": ".conf", "meme_type": "text/plain"},
  {"extension": ".cpio", "meme_type": "application/x-cpio"},
  {"extension": ".cpt", "meme_type": "application/mac-compactpro"},
  {"extension": ".crd", "meme_type": "application/x-mscardfile"},
  {"extension": ".crl", "meme_type": "application/pkix-crl"},
  {"extension": ".crt", "meme_type": "application/x-x509-ca-cert"},
  {"extension": ".csh", "meme_type": "application/x-csh"},
  {"extension": ".csml", "meme_type": "chemical/x-csml"},
  {"extension": ".csp", "meme_type": "application/vnd.commonspace"},
  {"extension": ".css", "meme_type": "text/css"},
  {"extension": ".csv", "meme_type": "text/csv"},
  {"extension": ".cu", "meme_type": "application/cu-seeme"},
  {"extension": ".curl", "meme_type": "text/vnd.curl"},
  {"extension": ".cww", "meme_type": "application/prs.cww"},
  {"extension": ".daf", "meme_type": "application/vnd.mobius.daf"},
  {"extension": ".dataless", "meme_type": "application/vnd.fdsn.seed"},
  {"extension": ".davmount", "meme_type": "application/davmount+xml"},
  {"extension": ".dcurl", "meme_type": "text/vnd.curl.dcurl"},
  {"extension": ".dd2", "meme_type": "application/vnd.oma.dd2+xml"},
  {"extension": ".ddd", "meme_type": "application/vnd.fujixerox.ddd"},
  {"extension": ".deb", "meme_type": "application/x-debian-package"},
  {"extension": ".dfac", "meme_type": "application/vnd.dreamfactory"},
  {"extension": ".dis", "meme_type": "application/vnd.mobius.dis"},
  {"extension": ".djv", "meme_type": "image/vnd.djvu"},
  {"extension": ".dna", "meme_type": "application/vnd.dna"},
  {"extension": ".doc", "meme_type": "application/msword"},
  {
    "extension": ".docm",
    "meme_type": "application/vnd.ms-word.document.macroenabled.12"
  },
  {
    "extension": ".docx",
    "meme_type":
        "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
  },
  {
    "extension": ".dotm",
    "meme_type": "application/vnd.ms-word.template.macroenabled.12"
  },
  {
    "extension": ".dotx",
    "meme_type":
        "application/vnd.openxmlformats-officedocument.wordprocessingml.template"
  },
  {"extension": ".dp", "meme_type": "application/vnd.osgi.dp"},
  {"extension": ".dpg", "meme_type": "application/vnd.dpgraph"},
  {"extension": ".dsc", "meme_type": "text/prs.lines.tag"},
  {"extension": ".dtb", "meme_type": "application/x-dtbook+xml"},
  {"extension": ".dtd", "meme_type": "application/xml-dtd"},
  {"extension": ".dts", "meme_type": "audio/vnd.dts"},
  {"extension": ".dtshd", "meme_type": "audio/vnd.dts.hd"},
  {"extension": ".dvi", "meme_type": "application/x-dvi"},
  {"extension": ".dwf", "meme_type": "model/vnd.dwf"},
  {"extension": ".dwg", "meme_type": "image/vnd.dwg"},
  {"extension": ".dxf", "meme_type": "image/vnd.dxf"},
  {"extension": ".dxp", "meme_type": "application/vnd.spotfire.dxp"},
  {"extension": ".ecelp4800", "meme_type": "audio/vnd.nuera.ecelp4800"},
  {"extension": ".ecelp7470", "meme_type": "audio/vnd.nuera.ecelp7470"},
  {"extension": ".ecelp9600", "meme_type": "audio/vnd.nuera.ecelp9600"},
  {"extension": ".ecma", "meme_type": "application/ecmascript"},
  {"extension": ".edm", "meme_type": "application/vnd.novadigm.edm"},
  {"extension": ".edx", "meme_type": "application/vnd.novadigm.edx"},
  {"extension": ".efif", "meme_type": "application/vnd.picsel"},
  {"extension": ".ei6", "meme_type": "application/vnd.pg.osasli"},
  {"extension": ".eml", "meme_type": "message/rfc822"},
  {"extension": ".emma", "meme_type": "application/emma+xml"},
  {"extension": ".eol", "meme_type": "audio/vnd.digital-winds"},
  {"extension": ".eot", "meme_type": "application/vnd.ms-fontobject"},
  {"extension": ".epub", "meme_type": "application/epub+zip"},
  {"extension": ".es3", "meme_type": "application/vnd.eszigno3+xml"},
  {"extension": ".esf", "meme_type": "application/vnd.epson.esf"},
  {"extension": ".etx", "meme_type": "text/x-setext"},
  {"extension": ".ext", "meme_type": "application/vnd.novadigm.ext"},
  {"extension": ".ez", "meme_type": "application/andrew-inset"},
  {"extension": ".ez2", "meme_type": "application/vnd.ezpix-album"},
  {"extension": ".ez3", "meme_type": "application/vnd.ezpix-package"},
  {"extension": ".f", "meme_type": "text/x-fortran"},
  {"extension": ".f4v", "meme_type": "video/x-f4v"},
  {"extension": ".fbs", "meme_type": "image/vnd.fastbidsheet"},
  {"extension": ".fdf", "meme_type": "application/vnd.fdf"},
  {
    "extension": ".fe_launch",
    "meme_type": "application/vnd.denovo.fcselayout-link"
  },
  {"extension": ".fg5", "meme_type": "application/vnd.fujitsu.oasysgp"},
  {"extension": ".fh", "meme_type": "image/x-freehand"},
  {"extension": ".fig", "meme_type": "application/x-xfig"},
  {"extension": ".fli", "meme_type": "video/x-fli"},
  {"extension": ".flo", "meme_type": "application/vnd.micrografx.flo"},
  {"extension": ".flv", "meme_type": "video/x-flv"},
  {"extension": ".flw", "meme_type": "application/vnd.kde.kivio"},
  {"extension": ".flx", "meme_type": "text/vnd.fmi.flexstor"},
  {"extension": ".fly", "meme_type": "text/vnd.fly"},
  {"extension": ".fnc", "meme_type": "application/vnd.frogans.fnc"},
  {"extension": ".fpx", "meme_type": "image/vnd.fpx"},
  {"extension": ".fsc", "meme_type": "application/vnd.fsc.weblaunch"},
  {"extension": ".fst", "meme_type": "image/vnd.fst"},
  {"extension": ".ftc", "meme_type": "application/vnd.fluxtime.clip"},
  {
    "extension": ".fti",
    "meme_type": "application/vnd.anser-web-funds-transfer-initiation"
  },
  {"extension": ".fvt", "meme_type": "video/vnd.fvt"},
  {"extension": ".fzs", "meme_type": "application/vnd.fuzzysheet"},
  {"extension": ".g3", "meme_type": "image/g3fax"},
  {"extension": ".gac", "meme_type": "application/vnd.groove-account"},
  {"extension": ".gdl", "meme_type": "model/vnd.gdl"},
  {"extension": ".geo", "meme_type": "application/vnd.dynageo"},
  {"extension": ".gex", "meme_type": "application/vnd.geometry-explorer"},
  {"extension": ".ggb", "meme_type": "application/vnd.geogebra.file"},
  {"extension": ".ggt", "meme_type": "application/vnd.geogebra.tool"},
  {"extension": ".ghf", "meme_type": "application/vnd.groove-help"},
  {"extension": ".gif", "meme_type": "image/gif"},
  {"extension": ".gim", "meme_type": "application/vnd.groove-identity-message"},
  {"extension": ".gmx", "meme_type": "application/vnd.gmx"},
  {"extension": ".gnumeric", "meme_type": "application/x-gnumeric"},
  {"extension": ".gph", "meme_type": "application/vnd.flographit"},
  {"extension": ".gqf", "meme_type": "application/vnd.grafeq"},
  {"extension": ".gram", "meme_type": "application/srgs"},
  {"extension": ".grv", "meme_type": "application/vnd.groove-injector"},
  {"extension": ".grxml", "meme_type": "application/srgs+xml"},
  {"extension": ".gsf", "meme_type": "application/x-font-ghostscript"},
  {"extension": ".gtar", "meme_type": "application/x-gtar"},
  {"extension": ".gtm", "meme_type": "application/vnd.groove-tool-message"},
  {"extension": ".gtw", "meme_type": "model/vnd.gtw"},
  {"extension": ".gv", "meme_type": "text/vnd.graphviz"},
  {"extension": ".gz", "meme_type": "application/x-gzip"},
  {"extension": ".h261", "meme_type": "video/h261"},
  {"extension": ".h263", "meme_type": "video/h263"},
  {"extension": ".h264", "meme_type": "video/h264"},
  {"extension": ".hbci", "meme_type": "application/vnd.hbci"},
  {"extension": ".hdf", "meme_type": "application/x-hdf"},
  {"extension": ".hlp", "meme_type": "application/winhlp"},
  {"extension": ".hpgl", "meme_type": "application/vnd.hp-hpgl"},
  {"extension": ".hpid", "meme_type": "application/vnd.hp-hpid"},
  {"extension": ".hps", "meme_type": "application/vnd.hp-hps"},
  {"extension": ".hqx", "meme_type": "application/mac-binhex40"},
  {"extension": ".htke", "meme_type": "application/vnd.kenameaapp"},
  {"extension": ".html", "meme_type": "text/html"},
  {"extension": ".hvd", "meme_type": "application/vnd.yamaha.hv-dic"},
  {"extension": ".hvp", "meme_type": "application/vnd.yamaha.hv-voice"},
  {"extension": ".hvs", "meme_type": "application/vnd.yamaha.hv-script"},
  {"extension": ".icc", "meme_type": "application/vnd.iccprofile"},
  {"extension": ".ice", "meme_type": "x-conference/x-cooltalk"},
  {"extension": ".ico", "meme_type": "image/x-icon"},
  {"extension": ".ics", "meme_type": "text/calendar"},
  {"extension": ".ief", "meme_type": "image/ief"},
  {"extension": ".ifm", "meme_type": "application/vnd.shana.informed.formdata"},
  {"extension": ".iges", "meme_type": "model/iges"},
  {"extension": ".igl", "meme_type": "application/vnd.igloader"},
  {"extension": ".igx", "meme_type": "application/vnd.micrografx.igx"},
  {
    "extension": ".iif",
    "meme_type": "application/vnd.shana.informed.interchange"
  },
  {"extension": ".imp", "meme_type": "application/vnd.accpac.simply.imp"},
  {"extension": ".ims", "meme_type": "application/vnd.ms-ims"},
  {"extension": ".ipk", "meme_type": "application/vnd.shana.informed.package"},
  {"extension": ".irm", "meme_type": "application/vnd.ibm.rights-management"},
  {"extension": ".irp", "meme_type": "application/vnd.irepository.package+xml"},
  {
    "extension": ".itp",
    "meme_type": "application/vnd.shana.informed.formtemplate"
  },
  {"extension": ".ivp", "meme_type": "application/vnd.immervision-ivp"},
  {"extension": ".ivu", "meme_type": "application/vnd.immervision-ivu"},
  {"extension": ".jad", "meme_type": "text/vnd.sun.j2me.app-descriptor"},
  {"extension": ".jam", "meme_type": "application/vnd.jam"},
  {"extension": ".jar", "meme_type": "application/java-archive"},
  {"extension": ".java", "meme_type": "text/x-java-source"},
  {"extension": ".jisp", "meme_type": "application/vnd.jisp"},
  {"extension": ".jlt", "meme_type": "application/vnd.hp-jlyt"},
  {"extension": ".jnlp", "meme_type": "application/x-java-jnlp-file"},
  {"extension": ".joda", "meme_type": "application/vnd.joost.joda-archive"},
  {"extension": ".jpe", "meme_type": "image/jpeg"},
  {"extension": ".jpgm", "meme_type": "video/jpm"},
  {"extension": ".jpgv", "meme_type": "video/jpeg"},
  {"extension": ".js", "meme_type": "application/javascript"},
  {"extension": ".json", "meme_type": "application/json"},
  {"extension": ".kar", "meme_type": "audio/midi"},
  {"extension": ".karbon", "meme_type": "application/vnd.kde.karbon"},
  {"extension": ".kfo", "meme_type": "application/vnd.kde.kformula"},
  {"extension": ".kia", "meme_type": "application/vnd.kidspiration"},
  {"extension": ".kil", "meme_type": "application/x-killustrator"},
  {"extension": ".kml", "meme_type": "application/vnd.google-earth.kml+xml"},
  {"extension": ".kmz", "meme_type": "application/vnd.google-earth.kmz"},
  {"extension": ".kne", "meme_type": "application/vnd.kinar"},
  {"extension": ".kon", "meme_type": "application/vnd.kde.kontour"},
  {"extension": ".kpr", "meme_type": "application/vnd.kde.kpresenter"},
  {"extension": ".ksp", "meme_type": "application/vnd.kde.kspread"},
  {"extension": ".ktr", "meme_type": "application/vnd.kahootz"},
  {"extension": ".kwd", "meme_type": "application/vnd.kde.kword"},
  {"extension": ".latex", "meme_type": "application/x-latex"},
  {
    "extension": ".lbd",
    "meme_type": "application/vnd.llamagraphics.life-balance.desktop"
  },
  {
    "extension": ".lbe",
    "meme_type": "application/vnd.llamagraphics.life-balance.exchange+xml"
  },
  {"extension": ".les", "meme_type": "application/vnd.hhe.lesson-player"},
  {"extension": ".link66", "meme_type": "application/vnd.route66.link66+xml"},
  {"extension": ".lostxml", "meme_type": "application/lost+xml"},
  {"extension": ".lrm", "meme_type": "application/vnd.ms-lrm"},
  {"extension": ".ltf", "meme_type": "application/vnd.frogans.ltf"},
  {"extension": ".lvp", "meme_type": "audio/vnd.lucent.voice"},
  {"extension": ".lwp", "meme_type": "application/vnd.lotus-wordpro"},
  {"extension": ".m13", "meme_type": "application/x-msmediaview"},
  {"extension": ".mpeg", "meme_type": "video/mpeg"},
  {"extension": ".mp3", "meme_type": "audio/mpeg"},
  {"extension": ".m3u", "meme_type": "audio/x-mpegurl"},
  {"extension": ".m4u", "meme_type": "video/vnd.mpegurl"},
  {"extension": ".m4v", "meme_type": "video/x-m4v"},
  {"extension": ".ma", "meme_type": "application/mathematica"},
  {"extension": ".mag", "meme_type": "application/vnd.ecowin.chart"},
  {"extension": ".man", "meme_type": "text/troff"},
  {"extension": ".mathml", "meme_type": "application/mathml+xml"},
  {"extension": ".mbk", "meme_type": "application/vnd.mobius.mbk"},
  {"extension": ".mbox", "meme_type": "application/mbox"},
  {"extension": ".mc1", "meme_type": "application/vnd.medcalcdata"},
  {"extension": ".mcd", "meme_type": "application/vnd.mcd"},
  {"extension": ".mcurl", "meme_type": "text/vnd.curl.mcurl"},
  {"extension": ".mdb", "meme_type": "application/x-msaccess"},
  {"extension": ".mdi", "meme_type": "image/vnd.ms-modi"},
  {"extension": ".mesh", "meme_type": "model/mesh"},
  {"extension": ".mfm", "meme_type": "application/vnd.mfmp"},
  {"extension": ".mgz", "meme_type": "application/vnd.proteus.magazine"},
  {"extension": ".mif", "meme_type": "application/vnd.mif"},
  {"extension": ".mj2", "meme_type": "video/mj2"},
  {"extension": ".mlp", "meme_type": "application/vnd.dolby.mlp"},
  {"extension": ".mmd", "meme_type": "application/vnd.chipnuts.karaoke-mmd"},
  {"extension": ".mmf", "meme_type": "application/vnd.smaf"},
  {"extension": ".mmr", "meme_type": "image/vnd.fujixerox.edmics-mmr"},
  {"extension": ".mny", "meme_type": "application/x-msmoney"},
  {"extension": ".mobi", "meme_type": "application/x-mobipocket-ebook"},
  {"extension": ".mov", "meme_type": "video/quicktime"},
  {"extension": ".movie", "meme_type": "video/x-sgi-movie"},
  {"extension": ".mp4", "meme_type": "video/mp4"},
  {"extension": ".mp4a", "meme_type": "audio/mp4"},
  {"extension": ".mp4s", "meme_type": "application/mp4"},
  {"extension": ".mpc", "meme_type": "application/vnd.mophun.certificate"},
  {"extension": ".mpkg", "meme_type": "application/vnd.apple.installer+xml"},
  {"extension": ".mpm", "meme_type": "application/vnd.blueice.multipass"},
  {"extension": ".mpn", "meme_type": "application/vnd.mophun.application"},
  {"extension": ".mpp", "meme_type": "application/vnd.ms-project"},
  {"extension": ".mpy", "meme_type": "application/vnd.ibm.minipay"},
  {"extension": ".mqy", "meme_type": "application/vnd.mobius.mqy"},
  {"extension": ".mrc", "meme_type": "application/marc"},
  {"extension": ".mscml", "meme_type": "application/mediaservercontrol+xml"},
  {"extension": ".mseed", "meme_type": "application/vnd.fdsn.mseed"},
  {"extension": ".mseq", "meme_type": "application/vnd.mseq"},
  {"extension": ".msf", "meme_type": "application/vnd.epson.msf"},
  {"extension": ".msl", "meme_type": "application/vnd.mobius.msl"},
  {"extension": ".msty", "meme_type": "application/vnd.muvee.style"},
  {"extension": ".mts", "meme_type": "model/vnd.mts"},
  {"extension": ".mus", "meme_type": "application/vnd.musician"},
  {
    "extension": ".musicxml",
    "meme_type": "application/vnd.recordare.musicxml+xml"
  },
  {"extension": ".mwf", "meme_type": "application/vnd.mfer"},
  {"extension": ".mxf", "meme_type": "application/mxf"},
  {"extension": ".mxl", "meme_type": "application/vnd.recordare.musicxml"},
  {"extension": ".mxml", "meme_type": "application/xv+xml"},
  {"extension": ".mxs", "meme_type": "application/vnd.triscape.mxs"},
  {
    "extension": ".n-gage,",
    "meme_type": "application/vnd.nokia.n-gage.symbian.install"
  },
  {"extension": ".ncx", "meme_type": "application/x-dtbncx+xml"},
  {"extension": ".ngdat", "meme_type": "application/vnd.nokia.n-gage.data"},
  {"extension": ".nlu", "meme_type": "application/vnd.neurolanguage.nlu"},
  {"extension": ".nml", "meme_type": "application/vnd.enliven"},
  {"extension": ".nnd", "meme_type": "application/vnd.noblenet-directory"},
  {"extension": ".nns", "meme_type": "application/vnd.noblenet-sealer"},
  {"extension": ".nnw", "meme_type": "application/vnd.noblenet-web"},
  {"extension": ".npx", "meme_type": "image/vnd.net-fpx"},
  {"extension": ".nsf", "meme_type": "application/vnd.lotus-notes"},
  {"extension": ".oa2", "meme_type": "application/vnd.fujitsu.oasys2"},
  {"extension": ".oa3", "meme_type": "application/vnd.fujitsu.oasys3"},
  {"extension": ".oas", "meme_type": "application/vnd.fujitsu.oasys"},
  {"extension": ".obd", "meme_type": "application/x-msbinder"},
  {"extension": ".oda", "meme_type": "application/oda"},
  {
    "extension": ".odb",
    "meme_type": "application/vnd.oasis.opendocument.database"
  },
  {
    "extension": ".odc",
    "meme_type": "application/vnd.oasis.opendocument.chart"
  },
  {
    "extension": ".odf",
    "meme_type": "application/vnd.oasis.opendocument.formula"
  },
  {
    "extension": ".odft",
    "meme_type": "application/vnd.oasis.opendocument.formula-template"
  },
  {
    "extension": ".odg",
    "meme_type": "application/vnd.oasis.opendocument.graphics"
  },
  {
    "extension": ".odi",
    "meme_type": "application/vnd.oasis.opendocument.image"
  },
  {
    "extension": ".odp",
    "meme_type": "application/vnd.oasis.opendocument.presentation"
  },
  {
    "extension": ".ods",
    "meme_type": "application/vnd.oasis.opendocument.spreadsheet"
  },
  {"extension": ".odt", "meme_type": "application/vnd.oasis.opendocument.text"},
  {"extension": ".oga", "meme_type": "audio/ogg"},
  {"extension": ".ogv", "meme_type": "video/ogg"},
  {"extension": ".ogx", "meme_type": "application/ogg"},
  {"extension": ".onepkg", "meme_type": "application/onenote"},
  {"extension": ".opf", "meme_type": "application/oebps-package+xml"},
  {"extension": ".oprc", "meme_type": "application/vnd.palm"},
  {"extension": ".org", "meme_type": "application/vnd.lotus-organizer"},
  {"extension": ".osf", "meme_type": "application/vnd.yamaha.openscoreformat"},
  {
    "extension": ".osfpvg",
    "meme_type": "application/vnd.yamaha.openscoreformat.osfpvg+xml"
  },
  {
    "extension": ".otc",
    "meme_type": "application/vnd.oasis.opendocument.chart-template"
  },
  {"extension": ".otf", "meme_type": "application/x-font-otf"},
  {
    "extension": ".otg",
    "meme_type": "application/vnd.oasis.opendocument.graphics-template"
  },
  {
    "extension": ".oth",
    "meme_type": "application/vnd.oasis.opendocument.text-web"
  },
  {
    "extension": ".oti",
    "meme_type": "application/vnd.oasis.opendocument.image-template"
  },
  {
    "extension": ".otm",
    "meme_type": "application/vnd.oasis.opendocument.text-master"
  },
  {
    "extension": ".otp",
    "meme_type": "application/vnd.oasis.opendocument.presentation-template"
  },
  {
    "extension": ".ots",
    "meme_type": "application/vnd.oasis.opendocument.spreadsheet-template"
  },
  {
    "extension": ".ott",
    "meme_type": "application/vnd.oasis.opendocument.text-template"
  },
  {"extension": ".oxt", "meme_type": "application/vnd.openofficeorg.extension"},
  {"extension": ".p", "meme_type": "text/x-pascal"},
  {"extension": ".p10", "meme_type": "application/pkcs10"},
  {"extension": ".p12", "meme_type": "application/x-pkcs12"},
  {"extension": ".p7b", "meme_type": "application/x-pkcs7-certificates"},
  {"extension": ".p7c", "meme_type": "application/pkcs7-mime"},
  {"extension": ".p7r", "meme_type": "application/x-pkcs7-certreqresp"},
  {"extension": ".p7s", "meme_type": "application/pkcs7-signature"},
  {"extension": ".pbd", "meme_type": "application/vnd.powerbuilder6"},
  {"extension": ".pbm", "meme_type": "image/x-portable-bitmap"},
  {"extension": ".pcf", "meme_type": "application/x-font-pcf"},
  {"extension": ".pcl", "meme_type": "application/vnd.hp-pcl"},
  {"extension": ".pclxl", "meme_type": "application/vnd.hp-pclxl"},
  {"extension": ".pct", "meme_type": "image/x-pict"},
  {"extension": ".pcurl", "meme_type": "application/vnd.curl.pcurl"},
  {"extension": ".pcx", "meme_type": "image/x-pcx"},
  {"extension": ".pdf", "meme_type": "application/pdf"},
  {"extension": ".pfr", "meme_type": "application/font-tdpfr"},
  {"extension": ".pgm", "meme_type": "image/x-portable-graymap"},
  {"extension": ".pgn", "meme_type": "application/x-chess-pgn"},
  {"extension": ".pgp", "meme_type": "application/pgp-encrypted"},
  {"extension": ".pki", "meme_type": "application/pkixcmp"},
  {"extension": ".pkipath", "meme_type": "application/pkix-pkipath"},
  {"extension": ".plb", "meme_type": "application/vnd.3gpp.pic-bw-large"},
  {"extension": ".plc", "meme_type": "application/vnd.mobius.plc"},
  {"extension": ".plf", "meme_type": "application/vnd.pocketlearn"},
  {"extension": ".pls", "meme_type": "application/pls+xml"},
  {"extension": ".pml", "meme_type": "application/vnd.ctc-posml"},
  {"extension": ".png", "meme_type": "image/png"},
  {"extension": ".pnm", "meme_type": "image/x-portable-anymap"},
  {"extension": ".portpkg", "meme_type": "application/vnd.macports.portpkg"},
  {"extension": ".pot", "meme_type": "application/vnd.ms-powerpoint"},
  {
    "extension": ".potm",
    "meme_type": "application/vnd.ms-powerpoint.template.macroenabled.12"
  },
  {
    "extension": ".potx",
    "meme_type":
        "application/vnd.openxmlformats-officedocument.presentationml.template"
  },
  {
    "extension": ".ppam",
    "meme_type": "application/vnd.ms-powerpoint.addin.macroenabled.12"
  },
  {"extension": ".ppd", "meme_type": "application/vnd.cups-ppd"},
  {"extension": ".ppm", "meme_type": "image/x-portable-pixmap"},
  {
    "extension": ".ppsm",
    "meme_type": "application/vnd.ms-powerpoint.slideshow.macroenabled.12"
  },
  {
    "extension": ".ppsx",
    "meme_type":
        "application/vnd.openxmlformats-officedocument.presentationml.slideshow"
  },
  {
    "extension": ".pptm",
    "meme_type": "application/vnd.ms-powerpoint.presentation.macroenabled.12"
  },
  {
    "extension": ".pptx",
    "meme_type":
        "application/vnd.openxmlformats-officedocument.presentationml.presentation"
  },
  {"extension": ".pre", "meme_type": "application/vnd.lotus-freelance"},
  {"extension": ".prf", "meme_type": "application/pics-rules"},
  {"extension": ".psb", "meme_type": "application/vnd.3gpp.pic-bw-small"},
  {"extension": ".psd", "meme_type": "image/vnd.adobe.photoshop"},
  {"extension": ".psf", "meme_type": "application/x-font-linux-psf"},
  {"extension": ".ptid", "meme_type": "application/vnd.pvi.ptid1"},
  {"extension": ".pub", "meme_type": "application/x-mspublisher"},
  {"extension": ".pvb", "meme_type": "application/vnd.3gpp.pic-bw-var"},
  {"extension": ".pwn", "meme_type": "application/vnd.3m.post-it-notes"},
  {"extension": ".py", "meme_type": "text/x-python"},
  {"extension": ".pya", "meme_type": "audio/vnd.ms-playready.media.pya"},
  {"extension": ".pyc", "meme_type": "application/x-python-code"},
  {"extension": ".pyv", "meme_type": "video/vnd.ms-playready.media.pyv"},
  {"extension": ".qam", "meme_type": "application/vnd.epson.quickanime"},
  {"extension": ".qbo", "meme_type": "application/vnd.intu.qbo"},
  {"extension": ".qfx", "meme_type": "application/vnd.intu.qfx"},
  {"extension": ".qps", "meme_type": "application/vnd.publishare-delta-tree"},
  {"extension": ".qwd", "meme_type": "application/vnd.quark.quarkxpress"},
  {"extension": ".ra", "meme_type": "audio/x-pn-realaudio"},
  {"extension": ".rar", "meme_type": "application/x-rar-compressed"},
  {"extension": ".ras", "meme_type": "image/x-cmu-raster"},
  {
    "extension": ".rcprofile",
    "meme_type": "application/vnd.ipunplugged.rcprofile"
  },
  {"extension": ".rdf", "meme_type": "application/rdf+xml"},
  {"extension": ".rdz", "meme_type": "application/vnd.data-vision.rdz"},
  {"extension": ".rep", "meme_type": "application/vnd.businessobjects"},
  {"extension": ".res", "meme_type": "application/x-dtbresource+xml"},
  {"extension": ".rgb", "meme_type": "image/x-rgb"},
  {"extension": ".rif", "meme_type": "application/reginfo+xml"},
  {"extension": ".rl", "meme_type": "application/resource-lists+xml"},
  {"extension": ".rlc", "meme_type": "image/vnd.fujixerox.edmics-rlc"},
  {"extension": ".rld", "meme_type": "application/resource-lists-diff+xml"},
  {"extension": ".rm", "meme_type": "application/vnd.rn-realmedia"},
  {"extension": ".rmp", "meme_type": "audio/x-pn-realaudio-plugin"},
  {"extension": ".rms", "meme_type": "application/vnd.jcp.javame.midlet-rms"},
  {"extension": ".rnc", "meme_type": "application/relax-ng-compact-syntax"},
  {"extension": ".rpm", "meme_type": "application/x-rpm"},
  {"extension": ".rpss", "meme_type": "application/vnd.nokia.radio-presets"},
  {"extension": ".rpst", "meme_type": "application/vnd.nokia.radio-preset"},
  {"extension": ".rq", "meme_type": "application/sparql-query"},
  {"extension": ".rs", "meme_type": "application/rls-services+xml"},
  {"extension": ".rsd", "meme_type": "application/rsd+xml"},
  {"extension": ".rss", "meme_type": "application/rss+xml"},
  {"extension": ".rtf", "meme_type": "application/rtf"},
  {"extension": ".rtx", "meme_type": "text/richtext"},
  {"extension": ".saf", "meme_type": "application/vnd.yamaha.smaf-audio"},
  {"extension": ".sbml", "meme_type": "application/sbml+xml"},
  {"extension": ".sc", "meme_type": "application/vnd.ibm.secure-container"},
  {"extension": ".scd", "meme_type": "application/x-msschedule"},
  {"extension": ".scm", "meme_type": "application/vnd.lotus-screencam"},
  {"extension": ".scq", "meme_type": "application/scvp-cv-request"},
  {"extension": ".scs", "meme_type": "application/scvp-cv-response"},
  {"extension": ".scurl", "meme_type": "text/vnd.curl.scurl"},
  {"extension": ".sda", "meme_type": "application/vnd.stardivision.draw"},
  {"extension": ".sdc", "meme_type": "application/vnd.stardivision.calc"},
  {"extension": ".sdd", "meme_type": "application/vnd.stardivision.impress"},
  {"extension": ".sdkd", "meme_type": "application/vnd.solent.sdkm+xml"},
  {"extension": ".sdp", "meme_type": "application/sdp"},
  {"extension": ".sdw", "meme_type": "application/vnd.stardivision.writer"},
  {"extension": ".see", "meme_type": "application/vnd.seemail"},
  {"extension": ".sema", "meme_type": "application/vnd.sema"},
  {"extension": ".semd", "meme_type": "application/vnd.semd"},
  {"extension": ".semf", "meme_type": "application/vnd.semf"},
  {"extension": ".ser", "meme_type": "application/java-serialized-object"},
  {"extension": ".setpay", "meme_type": "application/set-payment-initiation"},
  {
    "extension": ".setreg",
    "meme_type": "application/set-registration-initiation"
  },
  {
    "extension": ".sfd-hdstx,",
    "meme_type": "application/vnd.hydrostatix.sof-data"
  },
  {"extension": ".sfs", "meme_type": "application/vnd.spotfire.sfs"},
  {
    "extension": ".sgl",
    "meme_type": "application/vnd.stardivision.writer-global"
  },
  {"extension": ".sgm", "meme_type": "text/sgml"},
  {"extension": ".sh", "meme_type": "application/x-sh"},
  {"extension": ".shar", "meme_type": "application/x-shar"},
  {"extension": ".shf", "meme_type": "application/shf+xml"},
  {"extension": ".si", "meme_type": "text/vnd.wap.si"},
  {"extension": ".sic", "meme_type": "application/vnd.wap.sic"},
  {"extension": ".sis", "meme_type": "application/vnd.symbian.install"},
  {"extension": ".sit", "meme_type": "application/x-stuffit"},
  {"extension": ".sitx", "meme_type": "application/x-stuffitx"},
  {"extension": ".skd", "meme_type": "application/vnd.koan"},
  {"extension": ".sl", "meme_type": "text/vnd.wap.sl"},
  {"extension": ".slc", "meme_type": "application/vnd.wap.slc"},
  {
    "extension": ".sldm",
    "meme_type": "application/vnd.ms-powerpoint.slide.macroenabled.12"
  },
  {
    "extension": ".sldx",
    "meme_type":
        "application/vnd.openxmlformats-officedocument.presentationml.slide"
  },
  {"extension": ".slt", "meme_type": "application/vnd.epson.salt"},
  {"extension": ".smf", "meme_type": "application/vnd.stardivision.math"},
  {"extension": ".smi", "meme_type": "application/smil+xml"},
  {"extension": ".snf", "meme_type": "application/x-font-snf"},
  {"extension": ".spf", "meme_type": "application/vnd.yamaha.smaf-phrase"},
  {"extension": ".spl", "meme_type": "application/x-futuresplash"},
  {"extension": ".spot", "meme_type": "text/vnd.in3d.spot"},
  {"extension": ".spp", "meme_type": "application/scvp-vp-response"},
  {"extension": ".spq", "meme_type": "application/scvp-vp-request"},
  {"extension": ".src", "meme_type": "application/x-wais-source"},
  {"extension": ".srx", "meme_type": "application/sparql-results+xml"},
  {"extension": ".sse", "meme_type": "application/vnd.kodak-descriptor"},
  {"extension": ".ssf", "meme_type": "application/vnd.epson.ssf"},
  {"extension": ".ssml", "meme_type": "application/ssml+xml"},
  {"extension": ".stc", "meme_type": "application/vnd.sun.xml.calc.template"},
  {"extension": ".std", "meme_type": "application/vnd.sun.xml.draw.template"},
  {"extension": ".stf", "meme_type": "application/vnd.wt.stf"},
  {
    "extension": ".sti",
    "meme_type": "application/vnd.sun.xml.impress.template"
  },
  {"extension": ".stk", "meme_type": "application/hyperstudio"},
  {"extension": ".stl", "meme_type": "application/vnd.ms-pki.stl"},
  {"extension": ".str", "meme_type": "application/vnd.pg.format"},
  {"extension": ".stw", "meme_type": "application/vnd.sun.xml.writer.template"},
  {"extension": ".sus", "meme_type": "application/vnd.sus-calendar"},
  {"extension": ".sv4cpio", "meme_type": "application/x-sv4cpio"},
  {"extension": ".sv4crc", "meme_type": "application/x-sv4crc"},
  {"extension": ".svd", "meme_type": "application/vnd.svd"},
  {"extension": ".svg", "meme_type": "image/svg+xml"},
  {"extension": ".swf", "meme_type": "application/x-shockwave-flash"},
  {"extension": ".swi", "meme_type": "application/vnd.arastra.swi"},
  {"extension": ".sxc", "meme_type": "application/vnd.sun.xml.calc"},
  {"extension": ".sxd", "meme_type": "application/vnd.sun.xml.draw"},
  {"extension": ".sxg", "meme_type": "application/vnd.sun.xml.writer.global"},
  {"extension": ".sxi", "meme_type": "application/vnd.sun.xml.impress"},
  {"extension": ".sxm", "meme_type": "application/vnd.sun.xml.math"},
  {"extension": ".sxw", "meme_type": "application/vnd.sun.xml.writer"},
  {
    "extension": ".tao",
    "meme_type": "application/vnd.tao.intent-module-archive"
  },
  {"extension": ".tar", "meme_type": "application/x-tar"},
  {"extension": ".tcap", "meme_type": "application/vnd.3gpp2.tcap"},
  {"extension": ".tcl", "meme_type": "application/x-tcl"},
  {"extension": ".teacher", "meme_type": "application/vnd.smart.teacher"},
  {"extension": ".tex", "meme_type": "application/x-tex"},
  {"extension": ".texi", "meme_type": "application/x-texinfo"},
  {"extension": ".tfm", "meme_type": "application/x-tex-tfm"},
  {"extension": ".tif", "meme_type": "image/tiff"},
  {"extension": ".tmo", "meme_type": "application/vnd.tmobile-livetv"},
  {"extension": ".torrent", "meme_type": "application/x-bittorrent"},
  {"extension": ".tpl", "meme_type": "application/vnd.groove-tool-template"},
  {"extension": ".tpt", "meme_type": "application/vnd.trid.tpt"},
  {"extension": ".tra", "meme_type": "application/vnd.trueapp"},
  {"extension": ".trm", "meme_type": "application/x-msterminal"},
  {"extension": ".tsv", "meme_type": "text/tab-separated-values"},
  {"extension": ".ttc", "meme_type": "application/x-font-ttf"},
  {"extension": ".twd", "meme_type": "application/vnd.simtech-mindmapper"},
  {"extension": ".txd", "meme_type": "application/vnd.genomatix.tuxedo"},
  {"extension": ".txf", "meme_type": "application/vnd.mobius.txf"},
  {"extension": ".ufd", "meme_type": "application/vnd.ufdl"},
  {"extension": ".umj", "meme_type": "application/vnd.umajin"},
  {"extension": ".unityweb", "meme_type": "application/vnd.unity"},
  {"extension": ".uoml", "meme_type": "application/vnd.uoml+xml"},
  {"extension": ".uri", "meme_type": "text/uri-list"},
  {"extension": ".ustar", "meme_type": "application/x-ustar"},
  {"extension": ".utz", "meme_type": "application/vnd.uiq.theme"},
  {"extension": ".uu", "meme_type": "text/x-uuencode"},
  {"extension": ".vcd", "meme_type": "application/x-cdlink"},
  {"extension": ".vcf", "meme_type": "text/x-vcard"},
  {"extension": ".vcg", "meme_type": "application/vnd.groove-vcard"},
  {"extension": ".vcs", "meme_type": "text/x-vcalendar"},
  {"extension": ".vcx", "meme_type": "application/vnd.vcx"},
  {"extension": ".vis", "meme_type": "application/vnd.visionary"},
  {"extension": ".viv", "meme_type": "video/vnd.vivo"},
  {"extension": ".vrml", "meme_type": "model/vrml"},
  {"extension": ".vsd", "meme_type": "application/vnd.visio"},
  {"extension": ".vsf", "meme_type": "application/vnd.vsf"},
  {"extension": ".vtu", "meme_type": "model/vnd.vtu"},
  {"extension": ".vxml", "meme_type": "application/voicexml+xml"},
  {"extension": ".wad", "meme_type": "application/x-doom"},
  {"extension": ".wav", "meme_type": "audio/x-wav"},
  {"extension": ".wax", "meme_type": "audio/x-ms-wax"},
  {"extension": ".wbmp", "meme_type": "image/vnd.wap.wbmp"},
  {"extension": ".wbs", "meme_type": "application/vnd.criticaltools.wbs+xml"},
  {"extension": ".wbxml", "meme_type": "application/vnd.wap.wbxml"},
  {"extension": ".wcm", "meme_type": "application/vnd.ms-works"},
  {"extension": ".wm", "meme_type": "video/x-ms-wm"},
  {"extension": ".wma", "meme_type": "audio/x-ms-wma"},
  {"extension": ".wmd", "meme_type": "application/x-ms-wmd"},
  {"extension": ".wmf", "meme_type": "application/x-msmetafile"},
  {"extension": ".wml", "meme_type": "text/vnd.wap.wml"},
  {"extension": ".wmlc", "meme_type": "application/vnd.wap.wmlc"},
  {"extension": ".wmls", "meme_type": "text/vnd.wap.wmlscript"},
  {"extension": ".wmlsc", "meme_type": "application/vnd.wap.wmlscriptc"},
  {"extension": ".wmv", "meme_type": "video/x-ms-wmv"},
  {"extension": ".wmx", "meme_type": "video/x-ms-wmx"},
  {"extension": ".wmz", "meme_type": "application/x-ms-wmz"},
  {"extension": ".wpd", "meme_type": "application/vnd.wordperfect"},
  {"extension": ".wpl", "meme_type": "application/vnd.ms-wpl"},
  {"extension": ".wqd", "meme_type": "application/vnd.wqd"},
  {"extension": ".wri", "meme_type": "application/x-mswrite"},
  {"extension": ".wsdl", "meme_type": "application/wsdl+xml"},
  {"extension": ".wspolicy", "meme_type": "application/wspolicy+xml"},
  {"extension": ".wtb", "meme_type": "application/vnd.webturbo"},
  {"extension": ".wvx", "meme_type": "video/x-ms-wvx"},
  {"extension": ".x3d", "meme_type": "application/vnd.hzn-3d-crossword"},
  {"extension": ".xap", "meme_type": "application/x-silverlight-app"},
  {"extension": ".xar", "meme_type": "application/vnd.xara"},
  {"extension": ".xbap", "meme_type": "application/x-ms-xbap"},
  {
    "extension": ".xbd",
    "meme_type": "application/vnd.fujixerox.docuworks.binder"
  },
  {"extension": ".xbm", "meme_type": "image/x-xbitmap"},
  {"extension": ".xdm", "meme_type": "application/vnd.syncml.dm+xml"},
  {"extension": ".xdp", "meme_type": "application/vnd.adobe.xdp+xml"},
  {"extension": ".xdw", "meme_type": "application/vnd.fujixerox.docuworks"},
  {"extension": ".xenc", "meme_type": "application/xenc+xml"},
  {"extension": ".xer", "meme_type": "application/patch-ops-error+xml"},
  {"extension": ".xfdf", "meme_type": "application/vnd.adobe.xfdf"},
  {"extension": ".xfdl", "meme_type": "application/vnd.xfdl"},
  {"extension": ".xht", "meme_type": "application/xhtml+xml"},
  {"extension": ".xif", "meme_type": "image/vnd.xiff"},
  {"extension": ".xla", "meme_type": "application/vnd.ms-excel"},
  {
    "extension": ".xlam",
    "meme_type": "application/vnd.ms-excel.addin.macroenabled.12"
  },
  {
    "extension": ".xlsb",
    "meme_type": "application/vnd.ms-excel.sheet.binary.macroenabled.12"
  },
  {
    "extension": ".xlsm",
    "meme_type": "application/vnd.ms-excel.sheet.macroenabled.12"
  },
  {
    "extension": ".xlsx",
    "meme_type":
        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
  },
  {
    "extension": ".xltm",
    "meme_type": "application/vnd.ms-excel.template.macroenabled.12"
  },
  {
    "extension": ".xltx",
    "meme_type":
        "application/vnd.openxmlformats-officedocument.spreadsheetml.template"
  },
  {"extension": ".xml", "meme_type": "application/xml"},
  {"extension": ".xo", "meme_type": "application/vnd.olpc-sugar"},
  {"extension": ".xop", "meme_type": "application/xop+xml"},
  {"extension": ".xpi", "meme_type": "application/x-xpinstall"},
  {"extension": ".xpm", "meme_type": "image/x-xpixmap"},
  {"extension": ".xpr", "meme_type": "application/vnd.is-xpr"},
  {"extension": ".xps", "meme_type": "application/vnd.ms-xpsdocument"},
  {"extension": ".xpw", "meme_type": "application/vnd.intercon.formnet"},
  {"extension": ".xslt", "meme_type": "application/xslt+xml"},
  {"extension": ".xsm", "meme_type": "application/vnd.syncml+xml"},
  {"extension": ".xspf", "meme_type": "application/xspf+xml"},
  {"extension": ".xul", "meme_type": "application/vnd.mozilla.xul+xml"},
  {"extension": ".xwd", "meme_type": "image/x-xwindowdump"},
  {"extension": ".xyz", "meme_type": "chemical/x-xyz"},
  {"extension": ".zaz", "meme_type": "application/vnd.zzazz.deck+xml"},
  {"extension": ".zip", "meme_type": "application/zip"},
  {"extension": ".zir", "meme_type": "application/vnd.zul"},
  {
    "extension": ".zmm",
    "meme_type": "application/vnd.handheld-entertainment+xml"
  }
];
